/**
 * Adeels's CalculatorLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core';
import {
  OperationsTypeEnum,
  operationsTypeEnumSchema,
} from '../models/operationsTypeEnum';
import { number } from '../schema';
import { BaseController } from './baseController';

export class AdeelSCalculatorController extends BaseController {
  /**
   * @param operation operation of the calculator
   * @param x         first operant
   * @param y         second operant
   * @return Response from the API call
   */
  async calculate(
    operation: OperationsTypeEnum,
    x: number,
    y: number,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<number>> {
    const req = this.createRequest('GET');
    req.baseUrl('default');
    const mapped = req.prepareArgs({
      operation: [operation, operationsTypeEnumSchema],
      x: [x, number()],
      y: [y, number()],
    });
    req.query('x', mapped.x);
    req.query('y', mapped.y);
    req.appendTemplatePath`/${mapped.operation}`;
    return req.callAsJson(number(), requestOptions);
  }
}
