/**
 * Adeels's CalculatorLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for OperationsTypeEnum
 */
export enum OperationsTypeEnum {
  ADD = 'SUM',
  SUBTRACT = 'SUBTRACT',
}

/**
 * Schema for OperationsTypeEnum
 */
export const operationsTypeEnumSchema: Schema<OperationsTypeEnum> = stringEnum(OperationsTypeEnum);
